import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

const Services = ({ posts }) => {
  const { products } = posts
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        {products.map((item) => {
          return (
            <div className='container' key={item._id}>
              <p>{item.category}</p>
              <p>{item.title}</p>

              <div className='image-box'></div>
              <Link href={`/services/[id]`} as={`/services/${item._id}`}>
                <button className='btn view'>View</button>
              </Link>
            </div>
          )
        })}
      </div>
    </>
  )
}

export default Services

export async function getStaticProps() {
  const res = await fetch(
    'https://boltsign.herokuapp.com/api/v1/products/static'
  )
  console.log(res)
  const posts = await res.json()

  return {
    props: {
      posts,
    },
  }
}
