import {
  FeatureSection,
  Landing,
  LandingSecond,
  LandingThird,
  ServicesSection,
} from '@/components/home'
import ContactSection from '@/components/home/ContactSection'

import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Wrapper>
        <Landing />
        <ServicesSection />
        <LandingSecond />
        <FeatureSection />
        <LandingThird />
        <ContactSection />
      </Wrapper>
    </>
  )
}

const Wrapper = styled.div``
