import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Wrapper>
        <button className='btn'>Hello button</button>

        <h1>Heading 1</h1>
        <h2>Heading 2</h2>
        <h3>Heading 3</h3>
        <h4>Heading 4</h4>
        <h5>Heading 5</h5>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Expedita
          deleniti repudiandae adipisci libero nulla sequi voluptatem fugiat id
          possimus quis hic, aut necessitatibus quae quisquam!
        </p>
      </Wrapper>
    </>
  )
}

const Wrapper = styled.div`
  background-color: pink;
`
