import Head from 'next/head'
import React from 'react'

const SinglePortFolio = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>SinglePortFolio</div>
    </>
  )
}

export default SinglePortFolio
